# Generated by Django 5.2.11 on 2026-02-18 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('data_emissao', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_tributos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('nfce', 'NFC-e')], max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UploadLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
    ]
