# Generated by Django 5.1.6 on 2026-02-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('data_emissao', models.DateTimeField()),
                ('autorizada', models.BooleanField(default=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_tributos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('nfce', 'NFC-e')], max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UploadLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalCFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfop', models.CharField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empresa')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfops', to='fiscal.notafiscal')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'cfop'], name='fiscal_nota_empresa_96443c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cnpj_invalido', 'CNPJ inválido'), ('duplicada', 'Duplicada'), ('xml_invalido', 'XML inválido'), ('nao_autorizada', 'Não autorizada')], max_length=30)),
                ('chave', models.CharField(max_length=44)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to='fiscal.uploadlote')),
            ],
            options={
                'indexes': [models.Index(fields=['lote', 'tipo'], name='fiscal_uplo_lote_id_f120f5_idx')],
            },
        ),
    ]
