# Generated by Django 5.1.6 on 2026-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalcfop',
            name='cest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
