# Generated by Django 5.2.11 on 2026-02-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cnpj_invalido', 'CNPJ inválido'), ('duplicada', 'Duplicada'), ('xml_invalido', 'XML inválido'), ('nao_autorizada', 'Não autorizada')], max_length=30)),
                ('chave', models.CharField(max_length=44)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to='fiscal.uploadlote')),
            ],
            options={
                'indexes': [models.Index(fields=['lote', 'tipo'], name='fiscal_uplo_lote_id_f120f5_idx')],
            },
        ),
    ]
