# Generated by Django 5.2.11 on 2026-02-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
